spring:
  application:
    name: ThuVienSo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thuvienso?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  address: 0.0.0.0
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
mini:
  url: http://192.168.2.77:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: thuvienso

jwt:
  valid-duration: 3600
  refreshable-duration: 360000
  signerKey: "aGUDzL2OOlvQcHJE5fpfzxv0w6MUZtFhF4IRZo+Tc/z5FnKjn8xxJvoot4OVj6LP"